# https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml
replicaCount: 1

config:
  alertmanager:
    hostport: "http://alertmanager-operated.kube-prometheus-stack.svc:9093"
    endpoint: "/api/v1/alerts"
    minimumpriority: ""
    mutualtls: false
    checkcert: true

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: falcosidekick.local
      paths:
        - path: /
          # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.)
          # pathType: Prefix

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

webui:
  enabled: false
  replicaCount: 1
  service:
    # type: LoadBalancer
    type: ClusterIP
    port: 2802
    nodePort: 30282
    targetPort: 2802
    annotations: {}
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: falcosidekick-ui.local
        paths:
        - path: /
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
