---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: non-gvisor
  name: non-gvisor
spec:
  containers:
  - image: nginx
    name: non-gvisor
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}